param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'
$rankingsRoot = Join-Path $ProjectRoot 'Content\rankings'
$statsRoot = Join-Path $ProjectRoot 'Content\compare\stats'
$housingPath = Join-Path $statsRoot 'housing.yaml'

function Read-RankingRows {
    param([Parameter(Mandatory)][string]$Path)

    $rows = [System.Collections.Generic.List[hashtable]]::new()
    $current = $null
    $inRows = $false

    foreach ($line in Get-Content -LiteralPath $Path) {
        if (-not $inRows) {
            if ($line -match '^\s+rows:\s*$') {
                $inRows = $true
            }
            continue
        }

        if ($line -match '^\S') {
            break
        }

        if ($line -match '^\s*-\s+([a-zA-Z0-9_]+):\s*(.*)$') {
            if ($null -ne $current) {
                $rows.Add($current)
            }
            $current = @{}
            $current[$Matches[1]] = Convert-YamlScalar $Matches[2]
            continue
        }

        if ($null -ne $current -and $line -match '^\s+([a-zA-Z0-9_]+):\s*(.*)$') {
            $current[$Matches[1]] = Convert-YamlScalar $Matches[2]
        }
    }

    if ($null -ne $current) {
        $rows.Add($current)
    }

    return $rows
}

function Convert-YamlScalar {
    param([AllowEmptyString()][string]$Value)

    $result = $Value.Trim()
    if ($result.Length -ge 2) {
        if (($result.StartsWith('"') -and $result.EndsWith('"')) -or
            ($result.StartsWith("'") -and $result.EndsWith("'"))) {
            $result = $result.Substring(1, $result.Length - 2)
        }
    }
    return $result
}

function Format-YamlScalar {
    param([AllowNull()][object]$Value)

    if ($null -eq $Value) {
        return 'null'
    }

    $text = [string]$Value
    if ($text -match '^-?\d+(\.\d+)?$') {
        return $text
    }

    return '"' + $text.Replace('\', '\\').Replace('"', '\"') + '"'
}

function New-CategoryStateMap {
    param([string[]]$StateOrder)

    $result = [ordered]@{}
    foreach ($slug in $StateOrder) {
        $result[$slug] = [ordered]@{}
    }
    return $result
}

function Import-RankingFields {
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Target,
        [Parameter(Mandatory)][string]$RelativePath,
        [Parameter(Mandatory)][System.Collections.IDictionary]$FieldMap
    )

    $path = Join-Path $rankingsRoot $RelativePath
    foreach ($row in Read-RankingRows -Path $path) {
        $slug = [string]$row['state_slug']
        if ([string]::IsNullOrWhiteSpace($slug) -or -not $Target.Contains($slug)) {
            continue
        }

        foreach ($sourceField in $FieldMap.Keys) {
            if ($row.ContainsKey($sourceField) -and -not [string]::IsNullOrWhiteSpace([string]$row[$sourceField])) {
                $targetField = $FieldMap[$sourceField]
                $value = $row[$sourceField]
                if ($targetField.EndsWith('_pct')) {
                    $value = ([string]$value).Trim().TrimEnd('%').TrimStart('+')
                }
                $Target[$slug][$targetField] = $value
            }
        }
    }
}

function Write-CategoryFile {
    param(
        [Parameter(Mandatory)][string]$FileName,
        [Parameter(Mandatory)][System.Collections.IDictionary]$StateMap,
        [Parameter(Mandatory)][string[]]$Sources
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Generated by Scripts/Sync-CompareStatsFromRankings.ps1.')
    $lines.Add('# Edit the ranking files listed below, then run the sync script again.')
    foreach ($source in $Sources) {
        $lines.Add("# Source: Content/rankings/$($source.Replace('\', '/'))")
    }

    foreach ($slug in $StateMap.Keys) {
        $fields = $StateMap[$slug]
        if ($fields.Count -eq 0) {
            continue
        }

        $lines.Add("${slug}:")
        foreach ($field in $fields.Keys) {
            $lines.Add("  ${field}: $(Format-YamlScalar $fields[$field])")
        }
    }

    $destination = Join-Path $statsRoot $FileName
    Set-Content -LiteralPath $destination -Value $lines -Encoding utf8NoBOM
    Write-Host "Wrote $FileName ($($StateMap.Keys.Count) states scanned)"
}

$stateOrder = Get-Content -LiteralPath $housingPath |
    Where-Object { $_ -match '^([a-z][a-z-]+):$' } |
    ForEach-Object { $Matches[1] }

$demographicsSources = @(
    'demographics\domestic-migration-by-state.yml',
    'demographics\states-by-population.yml'
)
$demographics = New-CategoryStateMap $stateOrder
Import-RankingFields $demographics $demographicsSources[0] ([ordered]@{
    net_migration = 'net_domestic_migration'
    migration_band = 'domestic_migration_band'
})
Import-RankingFields $demographics $demographicsSources[1] ([ordered]@{
    population = 'population_estimate_2025'
    change_2020 = 'population_change_since_2020_pct'
})
Write-CategoryFile 'demographics-rankings.yaml' $demographics $demographicsSources

$geographySources = @(
    'geography\highest-point-by-state.yml',
    'geography\windiest-states-in-the-us.yml',
    'geography\most-likely-to-be-struck-by-lightning.yml'
)
$geography = New-CategoryStateMap $stateOrder
Import-RankingFields $geography $geographySources[0] ([ordered]@{
    highest_point = 'highest_point_name'
    elevation_ft = 'highest_point_elevation_ft'
})
Import-RankingFields $geography $geographySources[1] ([ordered]@{
    avg_wind_speed_mph = 'average_wind_speed_mph'
})
Import-RankingFields $geography $geographySources[2] ([ordered]@{
    lightning_density_per_sq_mile = 'lightning_density_per_sq_mile'
})
Write-CategoryFile 'geography-rankings.yaml' $geography $geographySources

$economySources = @(
    'economy\single-person-living-wage.yml',
    'economy\average-credit-score-by-state.yml'
)
$economy = New-CategoryStateMap $stateOrder
Import-RankingFields $economy $economySources[0] ([ordered]@{
    income_needed_2025 = 'single_person_living_wage'
    change_from_2024_pct = 'single_person_living_wage_change_pct'
})
Import-RankingFields $economy $economySources[1] ([ordered]@{
    score_2025 = 'average_credit_score'
})
Write-CategoryFile 'economy-rankings.yaml' $economy $economySources

$taxSources = @(
    'taxes\grocery-tax-by-state.yml',
    'taxes\death-tax-states.yml',
    'taxes\vehicle-property-tax-by-state.yml'
)
$taxes = New-CategoryStateMap $stateOrder
Import-RankingFields $taxes $taxSources[0] ([ordered]@{
    grocery_tax = 'grocery_tax_status'
    rate_numeric = 'grocery_tax_rate_pct'
})
Import-RankingFields $taxes $taxSources[1] ([ordered]@{
    death_tax_status = 'death_tax_status'
    estate_tax = 'estate_tax_status'
    inheritance_tax = 'inheritance_tax_status'
})
Import-RankingFields $taxes $taxSources[2] ([ordered]@{
    status = 'vehicle_property_tax_status'
})
Write-CategoryFile 'taxes-rankings.yaml' $taxes $taxSources

$healthSources = @(
    'health\infant-mortality-rate-by-state.yml',
    'health\drug-overdose-death-rate-by-state.yml'
)
$health = New-CategoryStateMap $stateOrder
Import-RankingFields $health $healthSources[0] ([ordered]@{
    rate = 'infant_mortality_rate_per_1000'
})
Import-RankingFields $health $healthSources[1] ([ordered]@{
    rate = 'overdose_death_rate_per_100k'
})
Write-CategoryFile 'health-rankings.yaml' $health $healthSources

$lawSources = @(
    'law\abortion-laws-by-state.yml',
    'law\right-to-work-states.yml'
)
$laws = New-CategoryStateMap $stateOrder
Import-RankingFields $laws $lawSources[0] ([ordered]@{
    status_summary = 'abortion_law_status'
    gestational_limit_weeks = 'abortion_gestational_limit'
})
Import-RankingFields $laws $lawSources[1] ([ordered]@{
    is_right_to_work = 'right_to_work_status'
})
Write-CategoryFile 'laws-rankings.yaml' $laws $lawSources

$cultureSources = @(
    'culture\casinos-by-state.yml',
    'culture\states-by-ufo-sightings.yml',
    'culture\most-popular-car-by-state.yml'
)
$culture = New-CategoryStateMap $stateOrder
Import-RankingFields $culture $cultureSources[0] ([ordered]@{
    casinos = 'casino_count'
    best_known_casino = 'best_known_casino'
})
Import-RankingFields $culture $cultureSources[1] ([ordered]@{
    total_sightings = 'ufo_sightings_total'
    per_100k = 'ufo_sightings_per_100k'
})
Import-RankingFields $culture $cultureSources[2] ([ordered]@{
    brand = 'most_popular_car_brand'
    model = 'most_popular_car_model'
})
Write-CategoryFile 'culture-rankings.yaml' $culture $cultureSources

$infrastructureSources = @(
    'infrastructure\water-quality-by-state.yml',
    'infrastructure\power-outages-by-state.yml',
    'infrastructure\road-quality-by-state.yml',
    'infrastructure\renewable-energy-by-state.yml',
    'infrastructure\largest-airport-by-state.yml'
)
$infrastructure = New-CategoryStateMap $stateOrder
Import-RankingFields $infrastructure $infrastructureSources[0] ([ordered]@{
    score = 'water_quality_score'
    grade = 'water_quality_grade'
})
Import-RankingFields $infrastructure $infrastructureSources[1] ([ordered]@{
    outage_hours = 'power_outage_hours_annual'
})
Import-RankingFields $infrastructure $infrastructureSources[2] ([ordered]@{
    rank = 'road_quality_rank'
})
Import-RankingFields $infrastructure $infrastructureSources[3] ([ordered]@{
    pct_renewable = 'renewable_electricity_pct'
})
Import-RankingFields $infrastructure $infrastructureSources[4] ([ordered]@{
    airport = 'largest_airport_name'
    iata = 'largest_airport_iata'
    passengers_millions = 'largest_airport_passengers_millions'
})
Write-CategoryFile 'infrastructure-rankings.yaml' $infrastructure $infrastructureSources
